package com.tss.formdesigner.dao.mysql;

import java.util.List;
import java.util.Map;

import com.tss.formdesigner.model.TsBo;

@FmdMyBatisRepository
public interface TsBoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_bo
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String boid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_bo
	 * @mbggenerated
	 */
	int insert(TsBo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_bo
	 * @mbggenerated
	 */
	int insertSelective(TsBo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_bo
	 * @mbggenerated
	 */
	TsBo selectByPrimaryKey(String boid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_bo
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(TsBo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_bo
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(TsBo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_bo
	 * @mbggenerated
	 */
	int updateByPrimaryKey(TsBo record);
	
	/**
     * query by object
     * @param record
     * @return
     */
    List<Map<String, ?>> pagingSelect(Map<String, Object> params);
    
    /**
     * query by object
     * @param record
     * @return
     */
    Map<String,?> pagingSelectCount(Map<String, Object> params);
}