package com.tss.formdesigner.dao.mysql;

import com.tss.formdesigner.model.TsFormVersion;
import com.tss.formdesigner.model.TsFormVersionKey;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

@MyBatisRepository
public interface TsFormVersionMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_form_version
     *
     * @mbggenerated Thu Jul 24 01:15:48 CST 2014
     */
    int deleteByPrimaryKey(TsFormVersionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_form_version
     *
     * @mbggenerated Thu Jul 24 01:15:48 CST 2014
     */
    int insert(TsFormVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_form_version
     *
     * @mbggenerated Thu Jul 24 01:15:48 CST 2014
     */
    int insertSelective(TsFormVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_form_version
     *
     * @mbggenerated Thu Jul 24 01:15:48 CST 2014
     */
    TsFormVersion selectByPrimaryKey(TsFormVersionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_form_version
     *
     * @mbggenerated Thu Jul 24 01:15:48 CST 2014
     */
    int updateByPrimaryKeySelective(TsFormVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_form_version
     *
     * @mbggenerated Thu Jul 24 01:15:48 CST 2014
     */
    int updateByPrimaryKeyWithBLOBs(TsFormVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_form_version
     *
     * @mbggenerated Thu Jul 24 01:15:48 CST 2014
     */
    int updateByPrimaryKey(TsFormVersion record);
    
    //============================= manual
    
    /**
     * Get max version id of a form
     * @param formid
     * @return
     */
    Map<String, ?> getMaxVersionid(@Param("formid") String formid);
    
    /**
     * query by object
     * @param record
     * @return
     */
    List<Map<String, ?>> pagingSelect(Map<String, Object> params);
    
    /**
     * query by object
     * @param record
     * @return
     */
    Map<String,?> pagingSelectCount(Map<String, Object> params);
}