package com.tss.formdesigner.dao.mysql;

import com.tss.formdesigner.model.TsFormRuntime;

public interface TsFormRuntimeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_form_runtime
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String rtid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_form_runtime
	 * @mbggenerated
	 */
	int insert(TsFormRuntime record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_form_runtime
	 * @mbggenerated
	 */
	int insertSelective(TsFormRuntime record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_form_runtime
	 * @mbggenerated
	 */
	TsFormRuntime selectByPrimaryKey(String rtid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_form_runtime
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(TsFormRuntime record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_form_runtime
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(TsFormRuntime record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_form_runtime
	 * @mbggenerated
	 */
	int updateByPrimaryKey(TsFormRuntime record);
}