package com.tss.formdesigner.dao.mysql;

import com.tss.formdesigner.model.TsForm;

import java.util.List;
import java.util.Map;

@FmdMyBatisRepository
public interface TsFormMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_form
     *
     * @mbggenerated Thu Jul 24 01:15:48 CST 2014
     */
    int deleteByPrimaryKey(String formid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_form
     *
     * @mbggenerated Thu Jul 24 01:15:48 CST 2014
     */
    int insert(TsForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_form
     *
     * @mbggenerated Thu Jul 24 01:15:48 CST 2014
     */
    int insertSelective(TsForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_form
     *
     * @mbggenerated Thu Jul 24 01:15:48 CST 2014
     */
    TsForm selectByPrimaryKey(String formid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_form
     *
     * @mbggenerated Thu Jul 24 01:15:48 CST 2014
     */
    int updateByPrimaryKeySelective(TsForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_form
     *
     * @mbggenerated Thu Jul 24 01:15:48 CST 2014
     */
    int updateByPrimaryKey(TsForm record);
    
    /**
     * query by object
     * @param record
     * @return
     */
    List<Map<String, ?>> pagingSelect(Map<String, Object> params);
    
    /**
     * query by object
     * @param record
     * @return
     */
    Map<String,?> pagingSelectCount(Map<String, Object> params);
}