package com.tss.formdesigner.dao.mysql;

import com.tss.formdesigner.model.TsFormHistory;
import com.tss.formdesigner.model.TsFormHistoryKey;
import com.tss.formdesigner.model.TsFormHistoryWithBLOBs;

import java.util.Map;

import org.apache.ibatis.annotations.Param;

@FmdMyBatisRepository
public interface TsFormHistoryMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_form_history
     *
     * @mbggenerated Thu Jul 24 01:15:48 CST 2014
     */
    int deleteByPrimaryKey(TsFormHistoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_form_history
     *
     * @mbggenerated Thu Jul 24 01:15:48 CST 2014
     */
    int insert(TsFormHistoryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_form_history
     *
     * @mbggenerated Thu Jul 24 01:15:48 CST 2014
     */
    int insertSelective(TsFormHistoryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_form_history
     *
     * @mbggenerated Thu Jul 24 01:15:48 CST 2014
     */
    TsFormHistoryWithBLOBs selectByPrimaryKey(TsFormHistoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_form_history
     *
     * @mbggenerated Thu Jul 24 01:15:48 CST 2014
     */
    int updateByPrimaryKeySelective(TsFormHistoryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_form_history
     *
     * @mbggenerated Thu Jul 24 01:15:48 CST 2014
     */
    int updateByPrimaryKeyWithBLOBs(TsFormHistoryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_form_history
     *
     * @mbggenerated Thu Jul 24 01:15:48 CST 2014
     */
    int updateByPrimaryKey(TsFormHistory record);
    
    //============================= manual
    
    /**
     * Get max version id of a form
     * @param formid
     * @return
     */
    Map<String, ?> getMaxChangeno(@Param("formid") String formid, @Param("versionid") String versionid);
}