package com.tss.formdesigner.model;

import java.util.Date;

public class TsBo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_bo.boid
	 * @mbggenerated
	 */
	private String boid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_bo.creator
	 * @mbggenerated
	 */
	private String creator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_bo.creatorname
	 * @mbggenerated
	 */
	private String creatorname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_bo.createtime
	 * @mbggenerated
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_bo.updatetime
	 * @mbggenerated
	 */
	private Date updatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_bo.changeuser
	 * @mbggenerated
	 */
	private String changeuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_bo.changeusername
	 * @mbggenerated
	 */
	private String changeusername;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_bo.boname
	 * @mbggenerated
	 */
	private String boname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_bo.bodesc
	 * @mbggenerated
	 */
	private String bodesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_bo.attrs
	 * @mbggenerated
	 */
	private String attrs;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_bo.boid
	 * @return  the value of ts_bo.boid
	 * @mbggenerated
	 */
	public String getBoid() {
		return boid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_bo.boid
	 * @param boid  the value for ts_bo.boid
	 * @mbggenerated
	 */
	public void setBoid(String boid) {
		this.boid = boid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_bo.creator
	 * @return  the value of ts_bo.creator
	 * @mbggenerated
	 */
	public String getCreator() {
		return creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_bo.creator
	 * @param creator  the value for ts_bo.creator
	 * @mbggenerated
	 */
	public void setCreator(String creator) {
		this.creator = creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_bo.creatorname
	 * @return  the value of ts_bo.creatorname
	 * @mbggenerated
	 */
	public String getCreatorname() {
		return creatorname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_bo.creatorname
	 * @param creatorname  the value for ts_bo.creatorname
	 * @mbggenerated
	 */
	public void setCreatorname(String creatorname) {
		this.creatorname = creatorname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_bo.createtime
	 * @return  the value of ts_bo.createtime
	 * @mbggenerated
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_bo.createtime
	 * @param createtime  the value for ts_bo.createtime
	 * @mbggenerated
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_bo.updatetime
	 * @return  the value of ts_bo.updatetime
	 * @mbggenerated
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_bo.updatetime
	 * @param updatetime  the value for ts_bo.updatetime
	 * @mbggenerated
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_bo.changeuser
	 * @return  the value of ts_bo.changeuser
	 * @mbggenerated
	 */
	public String getChangeuser() {
		return changeuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_bo.changeuser
	 * @param changeuser  the value for ts_bo.changeuser
	 * @mbggenerated
	 */
	public void setChangeuser(String changeuser) {
		this.changeuser = changeuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_bo.changeusername
	 * @return  the value of ts_bo.changeusername
	 * @mbggenerated
	 */
	public String getChangeusername() {
		return changeusername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_bo.changeusername
	 * @param changeusername  the value for ts_bo.changeusername
	 * @mbggenerated
	 */
	public void setChangeusername(String changeusername) {
		this.changeusername = changeusername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_bo.boname
	 * @return  the value of ts_bo.boname
	 * @mbggenerated
	 */
	public String getBoname() {
		return boname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_bo.boname
	 * @param boname  the value for ts_bo.boname
	 * @mbggenerated
	 */
	public void setBoname(String boname) {
		this.boname = boname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_bo.bodesc
	 * @return  the value of ts_bo.bodesc
	 * @mbggenerated
	 */
	public String getBodesc() {
		return bodesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_bo.bodesc
	 * @param bodesc  the value for ts_bo.bodesc
	 * @mbggenerated
	 */
	public void setBodesc(String bodesc) {
		this.bodesc = bodesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_bo.attrs
	 * @return  the value of ts_bo.attrs
	 * @mbggenerated
	 */
	public String getAttrs() {
		return attrs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_bo.attrs
	 * @param attrs  the value for ts_bo.attrs
	 * @mbggenerated
	 */
	public void setAttrs(String attrs) {
		this.attrs = attrs;
	}
}