package com.tss.formdesigner.model;

import java.util.Date;

public class TsFormVersion extends TsFormVersionKey {

	public static final String STATUS_ACTIVE = "00";
	public static final String STATUS_DEACTIVE = "01";
	public static final String STATUS_DISCARD = "02";
	public static final String CURRENT = "CURRENT";
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_form_version.VERSIONNAME
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	private String versionname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_form_version.VERSIONDESC
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	private String versiondesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_form_version.CREATETIME
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_form_version.UPDATETIME
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	private Date updatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_form_version.ISDEFAULT
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	private String isdefault;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_form_version.STATUS
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_form_version.CHECKOUTBY
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	private String checkoutby;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_form_version.CHECKOUTBYNAME
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	private String checkoutbyname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_form_version.CREATOR
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	private String creator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_form_version.CREATORNAME
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	private String creatorname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_form_version.FORMDATA
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	private String formdata;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_form_version.VERSIONNAME
	 * @return  the value of ts_form_version.VERSIONNAME
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	public String getVersionname() {
		return versionname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_form_version.VERSIONNAME
	 * @param versionname  the value for ts_form_version.VERSIONNAME
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	public void setVersionname(String versionname) {
		this.versionname = versionname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_form_version.VERSIONDESC
	 * @return  the value of ts_form_version.VERSIONDESC
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	public String getVersiondesc() {
		return versiondesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_form_version.VERSIONDESC
	 * @param versiondesc  the value for ts_form_version.VERSIONDESC
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	public void setVersiondesc(String versiondesc) {
		this.versiondesc = versiondesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_form_version.CREATETIME
	 * @return  the value of ts_form_version.CREATETIME
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_form_version.CREATETIME
	 * @param createtime  the value for ts_form_version.CREATETIME
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_form_version.UPDATETIME
	 * @return  the value of ts_form_version.UPDATETIME
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_form_version.UPDATETIME
	 * @param updatetime  the value for ts_form_version.UPDATETIME
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_form_version.ISDEFAULT
	 * @return  the value of ts_form_version.ISDEFAULT
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	public String getIsdefault() {
		return isdefault;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_form_version.ISDEFAULT
	 * @param isdefault  the value for ts_form_version.ISDEFAULT
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	public void setIsdefault(String isdefault) {
		this.isdefault = isdefault;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_form_version.STATUS
	 * @return  the value of ts_form_version.STATUS
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_form_version.STATUS
	 * @param status  the value for ts_form_version.STATUS
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_form_version.CHECKOUTBY
	 * @return  the value of ts_form_version.CHECKOUTBY
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	public String getCheckoutby() {
		return checkoutby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_form_version.CHECKOUTBY
	 * @param checkoutby  the value for ts_form_version.CHECKOUTBY
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	public void setCheckoutby(String checkoutby) {
		this.checkoutby = checkoutby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_form_version.CHECKOUTBYNAME
	 * @return  the value of ts_form_version.CHECKOUTBYNAME
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	public String getCheckoutbyname() {
		return checkoutbyname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_form_version.CHECKOUTBYNAME
	 * @param checkoutbyname  the value for ts_form_version.CHECKOUTBYNAME
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	public void setCheckoutbyname(String checkoutbyname) {
		this.checkoutbyname = checkoutbyname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_form_version.CREATOR
	 * @return  the value of ts_form_version.CREATOR
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	public String getCreator() {
		return creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_form_version.CREATOR
	 * @param creator  the value for ts_form_version.CREATOR
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	public void setCreator(String creator) {
		this.creator = creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_form_version.CREATORNAME
	 * @return  the value of ts_form_version.CREATORNAME
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	public String getCreatorname() {
		return creatorname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_form_version.CREATORNAME
	 * @param creatorname  the value for ts_form_version.CREATORNAME
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	public void setCreatorname(String creatorname) {
		this.creatorname = creatorname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_form_version.FORMDATA
	 * @return  the value of ts_form_version.FORMDATA
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	public String getFormdata() {
		return formdata;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_form_version.FORMDATA
	 * @param formdata  the value for ts_form_version.FORMDATA
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	public void setFormdata(String formdata) {
		this.formdata = formdata;
	}
}