package com.tss.formdesigner.model;

import java.util.Date;

public class TsForm {
	
	public static final String STATUS_ACTIVE = "00";
	public static final String STATUS_DEACTIVE = "01";
	public static final String STATUS_DISCARD = "02";
	
	public static final String TYPE_PROCESS = "PROCESS";
	public static final String TYPE_DATAEDIT = "DATAEDIT";

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_form.FORMID
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	private String formid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_form.FORMNAME
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	private String formname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_form.FORMDESC
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	private String formdesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_form.CREATOR
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	private String creator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_form.CREATORNAME
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	private String creatorname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_form.CREATETIME
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_form.FORMTYPE
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	private String formtype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_form.STATUS
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	private String status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_form.FORMID
	 * @return  the value of ts_form.FORMID
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	public String getFormid() {
		return formid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_form.FORMID
	 * @param formid  the value for ts_form.FORMID
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	public void setFormid(String formid) {
		this.formid = formid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_form.FORMNAME
	 * @return  the value of ts_form.FORMNAME
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	public String getFormname() {
		return formname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_form.FORMNAME
	 * @param formname  the value for ts_form.FORMNAME
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	public void setFormname(String formname) {
		this.formname = formname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_form.FORMDESC
	 * @return  the value of ts_form.FORMDESC
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	public String getFormdesc() {
		return formdesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_form.FORMDESC
	 * @param formdesc  the value for ts_form.FORMDESC
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	public void setFormdesc(String formdesc) {
		this.formdesc = formdesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_form.CREATOR
	 * @return  the value of ts_form.CREATOR
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	public String getCreator() {
		return creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_form.CREATOR
	 * @param creator  the value for ts_form.CREATOR
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	public void setCreator(String creator) {
		this.creator = creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_form.CREATORNAME
	 * @return  the value of ts_form.CREATORNAME
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	public String getCreatorname() {
		return creatorname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_form.CREATORNAME
	 * @param creatorname  the value for ts_form.CREATORNAME
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	public void setCreatorname(String creatorname) {
		this.creatorname = creatorname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_form.CREATETIME
	 * @return  the value of ts_form.CREATETIME
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_form.CREATETIME
	 * @param createtime  the value for ts_form.CREATETIME
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_form.FORMTYPE
	 * @return  the value of ts_form.FORMTYPE
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	public String getFormtype() {
		return formtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_form.FORMTYPE
	 * @param formtype  the value for ts_form.FORMTYPE
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	public void setFormtype(String formtype) {
		this.formtype = formtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_form.STATUS
	 * @return  the value of ts_form.STATUS
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_form.STATUS
	 * @param status  the value for ts_form.STATUS
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	public void setStatus(String status) {
		this.status = status;
	}
}