package com.tss.formdesigner.model;

public class TsFormRuntime {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_form_runtime.RTID
     *
     * @mbggenerated Wed Aug 06 11:05:34 CST 2014
     */
    private String rtid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_form_runtime.RTNAME
     *
     * @mbggenerated Wed Aug 06 11:05:34 CST 2014
     */
    private String rtname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_form_runtime.RTDESC
     *
     * @mbggenerated Wed Aug 06 11:05:34 CST 2014
     */
    private String rtdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_form_runtime.RTCONF
     *
     * @mbggenerated Wed Aug 06 11:05:34 CST 2014
     */
    private String rtconf;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_form_runtime.RTID
     *
     * @return the value of ts_form_runtime.RTID
     *
     * @mbggenerated Wed Aug 06 11:05:34 CST 2014
     */
    public String getRtid() {
        return rtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_form_runtime.RTID
     *
     * @param rtid the value for ts_form_runtime.RTID
     *
     * @mbggenerated Wed Aug 06 11:05:34 CST 2014
     */
    public void setRtid(String rtid) {
        this.rtid = rtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_form_runtime.RTNAME
     *
     * @return the value of ts_form_runtime.RTNAME
     *
     * @mbggenerated Wed Aug 06 11:05:34 CST 2014
     */
    public String getRtname() {
        return rtname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_form_runtime.RTNAME
     *
     * @param rtname the value for ts_form_runtime.RTNAME
     *
     * @mbggenerated Wed Aug 06 11:05:34 CST 2014
     */
    public void setRtname(String rtname) {
        this.rtname = rtname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_form_runtime.RTDESC
     *
     * @return the value of ts_form_runtime.RTDESC
     *
     * @mbggenerated Wed Aug 06 11:05:34 CST 2014
     */
    public String getRtdesc() {
        return rtdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_form_runtime.RTDESC
     *
     * @param rtdesc the value for ts_form_runtime.RTDESC
     *
     * @mbggenerated Wed Aug 06 11:05:34 CST 2014
     */
    public void setRtdesc(String rtdesc) {
        this.rtdesc = rtdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_form_runtime.RTCONF
     *
     * @return the value of ts_form_runtime.RTCONF
     *
     * @mbggenerated Wed Aug 06 11:05:34 CST 2014
     */
    public String getRtconf() {
        return rtconf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_form_runtime.RTCONF
     *
     * @param rtconf the value for ts_form_runtime.RTCONF
     *
     * @mbggenerated Wed Aug 06 11:05:34 CST 2014
     */
    public void setRtconf(String rtconf) {
        this.rtconf = rtconf;
    }
}