package com.tss.formdesigner.model;

public class TsFormVersionKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_form_version.FORMID
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	private String formid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_form_version.VERSIONID
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	private String versionid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_form_version.FORMID
	 * @return  the value of ts_form_version.FORMID
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	public String getFormid() {
		return formid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_form_version.FORMID
	 * @param formid  the value for ts_form_version.FORMID
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	public void setFormid(String formid) {
		this.formid = formid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_form_version.VERSIONID
	 * @return  the value of ts_form_version.VERSIONID
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	public String getVersionid() {
		return versionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_form_version.VERSIONID
	 * @param versionid  the value for ts_form_version.VERSIONID
	 * @mbggenerated  Sun Aug 03 23:07:05 CST 2014
	 */
	public void setVersionid(String versionid) {
		this.versionid = versionid;
	}
}