package com.tss.formdesigner.model;

import java.util.Date;

public class TsFormHistory extends TsFormHistoryKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_form_history.UPDATETIME
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	private Date updatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_form_history.ISAUTOSAVE
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	private String isautosave;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_form_history.VERSIONID
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	private String versionid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_form_history.CHANGEUSERID
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	private String changeuserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ts_form_history.CHANGEUSERNAME
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	private String changeusername;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_form_history.UPDATETIME
	 * @return  the value of ts_form_history.UPDATETIME
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_form_history.UPDATETIME
	 * @param updatetime  the value for ts_form_history.UPDATETIME
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_form_history.ISAUTOSAVE
	 * @return  the value of ts_form_history.ISAUTOSAVE
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	public String getIsautosave() {
		return isautosave;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_form_history.ISAUTOSAVE
	 * @param isautosave  the value for ts_form_history.ISAUTOSAVE
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	public void setIsautosave(String isautosave) {
		this.isautosave = isautosave;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_form_history.VERSIONID
	 * @return  the value of ts_form_history.VERSIONID
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	public String getVersionid() {
		return versionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_form_history.VERSIONID
	 * @param versionid  the value for ts_form_history.VERSIONID
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	public void setVersionid(String versionid) {
		this.versionid = versionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_form_history.CHANGEUSERID
	 * @return  the value of ts_form_history.CHANGEUSERID
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	public String getChangeuserid() {
		return changeuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_form_history.CHANGEUSERID
	 * @param changeuserid  the value for ts_form_history.CHANGEUSERID
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	public void setChangeuserid(String changeuserid) {
		this.changeuserid = changeuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ts_form_history.CHANGEUSERNAME
	 * @return  the value of ts_form_history.CHANGEUSERNAME
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	public String getChangeusername() {
		return changeusername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ts_form_history.CHANGEUSERNAME
	 * @param changeusername  the value for ts_form_history.CHANGEUSERNAME
	 * @mbggenerated  Mon Aug 04 17:27:05 CST 2014
	 */
	public void setChangeusername(String changeusername) {
		this.changeusername = changeusername;
	}
}