package com.tss.formdesigner.model;

public class TsFormHistoryWithBLOBs extends TsFormHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_form_history.FORMDATA
     *
     * @mbggenerated Thu Jul 24 01:15:48 CST 2014
     */
    private String formdata;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_form_history.CHANGING
     *
     * @mbggenerated Thu Jul 24 01:15:48 CST 2014
     */
    private String changing;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_form_history.FORMDATA
     *
     * @return the value of ts_form_history.FORMDATA
     *
     * @mbggenerated Thu Jul 24 01:15:48 CST 2014
     */
    public String getFormdata() {
        return formdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_form_history.FORMDATA
     *
     * @param formdata the value for ts_form_history.FORMDATA
     *
     * @mbggenerated Thu Jul 24 01:15:48 CST 2014
     */
    public void setFormdata(String formdata) {
        this.formdata = formdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_form_history.CHANGING
     *
     * @return the value of ts_form_history.CHANGING
     *
     * @mbggenerated Thu Jul 24 01:15:48 CST 2014
     */
    public String getChanging() {
        return changing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_form_history.CHANGING
     *
     * @param changing the value for ts_form_history.CHANGING
     *
     * @mbggenerated Thu Jul 24 01:15:48 CST 2014
     */
    public void setChanging(String changing) {
        this.changing = changing;
    }
}